name: Shrine
description: Get the food you like.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  scoped_model: ^0.3.0
  shrine_images: ^1.0.0
  mailer: ^3.0.1
  stepper_touch: ^0.0.1
  wave_progress_widget: ^0.0.1
  connectivity: ^0.4.3+6
  groovin_material_icons: ^1.1.6
  flutter_masked_text: ^0.8.0
  intro_views_flutter: ^2.6.0
  shared_preferences: ^0.5.3+4
  fancy_bottom_navigation: ^0.3.2
  rflutter_alert: ^1.0.3
  http: ^0.12.0+2
  wordpress_api: ^0.1.2+5
  flutter_spinkit: "^2.1.0"
  flutter_wordpress: ^0.1.4
  progress_dialog: ^1.1.0+1


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons: 
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  ios: true
  android: true
  


flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/slanted_menu.png
    - assets/menu_background.jpg
    - assets/pizza.png
    - assets/logo_white.png
    - assets/logo_white2.png
    - assets/favorite_food.png
    - assets/logo.png


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
    - family: MyFont
      fonts:
        - asset: assets/Fonts/sspu.ttf    
    - family: GogoiaDec
      fonts:
        - asset: assets/Fonts/gogoia-dec.otf 
    - family: Greece
      fonts:
        - asset: assets/Fonts/greece.ttf 
    - family: Karmina
      fonts:
        - asset: assets/Fonts/Karmina.ttf 
    - family: SenseiMedium
      fonts:
        - asset: assets/Fonts/sensei-medium.ttf  

